version: "3"

services:

  exile_platform:

    image: exile_platform

    container_name: exile_platform

    volumes:

      - /srv/test_reports:/srv/test_reports

    network_mode: "host"

    depends_on:

networks:


